# fly.toml
app = "quizz-app-backend"

[build]
# Para usar Dockerfile existente
dockerfile = "Dockerfile"

[env]
# Spring Boot usa a porta 8080 por padrão
PORT = "8080"

[deploy]
release_command = ""

[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]
